#!/bin/bash
REPS=100
DSIZE=200
ND=100
NM_MIN=-0.9
NM_MAX=0.525
NM_GRID_SIZE=4
COST=10.0
B_MIN=1333.33
B_MAX=2666.67
B_GRID_SIZE=5
EXPTAG=20250725
WORKDIR=$SCRATCH/paral_metapop/Base/$EXPTAG
LOGDIR=$WORKDIR/logs
OUTPUT=$WORKDIR/sims
BASEDIR=$(dirname "$PWD")
ACCOUNT=coa_jva238_uksr
TIME=14-00:00:00
NTASKS=40
if [ ! -d "$WORKDIR" ]; then
    mkdir -p $WORKDIR
fi
if [ ! -d "$LOGDIR" ]; then
    mkdir -p $LOGDIR
fi
if [ ! -d "$OUTPUT" ]; then
    mkdir -p $OUTPUT
fi
SCRIPT=$BASEDIR/run_A9.sbatch
echo "sbatch -D $WORKDIR --ntasks $NTASKS --export=ALL,BASEDIR=$BASEDIR,REPS=$REPS,DSIZE=$DSIZE,ND=$ND,NM_MIN=$NM_MIN,NM_MAX=$NM_MAX,NM_GRID_SIZE=$NM_GRID_SIZE,COST=$COST,B_MIN=$B_MIN,B_MAX=$B_MAX,B_GRID_SIZE=$B_GRID_SIZE,OUTPUT=$OUTPUT $SCRIPT"
sbatch -D $WORKDIR --ntasks $NTASKS --export=ALL,BASEDIR=$BASEDIR,REPS=$REPS,DSIZE=$DSIZE,ND=$ND,NM_MIN=$NM_MIN,NM_MAX=$NM_MAX,NM_GRID_SIZE=$NM_GRID_SIZE,COST=$COST,B_MIN=$B_MIN,B_MAX=$B_MAX,B_GRID_SIZE=$B_GRID_SIZE,OUTPUT=$OUTPUT $SCRIPT